### ISSUE TITLE
CSync Dependancy update/change

### ISSUE THREAD

**Issue by Slendykins** [SylviBlossom/LC-CustomWormTiming#1]
Hey Sylvi!

Just a heads up that CSync is deprecated and is no longer updated or supported,

A fork of CSync is available that other mods are moving to as a replacement;

https://thunderstore.io/c/lethal-company/p/Sigurd/CSync/

**Comment by SylviBlossom** [comment]
thanks! just got that dependency updated

**Comment by Owen3H** [comment]
> Hey Sylvi!
> 
> Just a heads up that CSync is deprecated and is no longer updated or supported,
> 
> A fork of CSync is available that other mods are moving to as a replacement;
> 
> https://thunderstore.io/c/lethal-company/p/Sigurd/CSync/

It is and will continue to be supported, just not on Thunderstore (at least not by me).
